---

- name: Run localhost inwx tasks
  hosts: localhost
  tasks:
    - name: Retrieve session for account with two factor authentication
      inwx.collection.session:
        username: "{{ lookup('env', 'ANSIBLE_INWX_USER') }}"
        password: "{{ lookup('env', 'ANSIBLE_INWX_PASS') }}"
        shared_secret: "{{ lookup('env', 'ANSIBLE_INWX_SECRET') }}"
        register: temp_session_output

    - name: Set inwx session as fact
      set_fact:
        inwx_session: "{{ temp_session_output.result.session }}"
        temp_session_result: # set to nothing

    - name: Ensure A record 'test' exists with prefetched API session
      inwx.collection.dns:
        domain: example.com
        type: A
        record: test
        value:
          - 1.2.3.4
        session: '{{ inwx_session }}'